name: galaxy_18_lottery_app
description: SuperApp Lottery Application
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  shared_preferences: ^2.2.1
  flutter_riverpod: ^2.4.0
  auto_route: ^7.8.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.7
  flutter_local_notifications: ^15.1.1
  permission_handler: ^11.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  fonts:
    - family: NotoSansLao
      fonts:
        - asset: lib/assets/fonts/NotoSansLao-Medium.ttf
        - asset: lib/assets/fonts/NotoSansLao-Light.ttf
    - family: roboto
      fonts:
        - asset: lib/assets/fonts/roboto.bold.ttf
        - asset: lib/assets/fonts/roboto.medium.ttf
        - asset: lib/assets/fonts/roboto.medium-italic.ttf
